### ISSUE TITLE
输入图片后报错

### ISSUE THREAD

**Issue by WindFlarer** [synodriver/nonebot_plugin_picsearcher#10]
![image](https://user-images.githubusercontent.com/94285370/141674450-30d2aafc-8156-494a-b5fe-a6a0d381e6d2.png)

**Comment by synodriver** [comment]
有完整的traceback吗？

**Comment by WindFlarer** [comment]
11-14 17:11:19 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_picsearcher, type=message, priority=0, temp=True&gt; failed.
Traceback (most recent call last):
&nbsp; File "C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\bot.py", line 42, in <module&gt;
&nbsp; &nbsp; nonebot.run(app="__mp_main__:app")
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 278, in run
&nbsp; &nbsp; get_driver().run(host, port, *args, **kwargs)
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 256, in run
&nbsp; &nbsp; uvicorn.run(
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 447, in run
&nbsp; &nbsp; server.run()
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 68, in run
&nbsp; &nbsp; return asyncio.run(self.serve(sockets=sockets))
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
&nbsp; &nbsp; return loop.run_until_complete(main)
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
&nbsp; &nbsp; self.run_forever()
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
&nbsp; &nbsp; self._run_once()
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
&nbsp; &nbsp; handle._run()
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
&nbsp; &nbsp; self._context.run(self._callback, *self._args)
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 128, in _check_matcher
&nbsp; &nbsp; await _run_matcher(Matcher, bot, event, state)
&gt; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 156, in _run_matcher
&nbsp; &nbsp; await matcher.run(bot, event, state)
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 597, in run
&nbsp; &nbsp; await handler(self, bot, event, self.state)
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\handler.py", line 64, in __call__
&nbsp; &nbsp; await self.func(
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 458, in wrapper
&nbsp; &nbsp; await func_handler(matcher, bot, event, state)
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\handler.py", line 64, in __call__
&nbsp; &nbsp; await self.func(
&nbsp; File "C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\nonebot_plugin_picsearcher\__init__.py", line 76, in get_setu
&nbsp; &nbsp; async for msg in limiter(get_des(url, mod), bot.config.search_limit or 2):
&nbsp; File "C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\nonebot_plugin_picsearcher\utils.py", line 9, in limiter
&nbsp; &nbsp; yield await gen.asend(None)
&nbsp; File "C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\nonebot_plugin_picsearcher\__init__.py", line 40, in get_des
&nbsp; &nbsp; async for msg in get_des_asc(url):
&nbsp; File "C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\nonebot_plugin_picsearcher\ascii2d.py", line 39, in get_des
&nbsp; &nbsp; image_data: List[Tuple] = await get_pic_from_url(url)
&nbsp; File "C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\nonebot_plugin_picsearcher\ascii2d.py", line 33, in get_pic_from_url
&nbsp; &nbsp; async with session.get(real_url, proxy=proxy) as resp:
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
&nbsp; &nbsp; self._resp = await self._coro
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 415, in _request
&nbsp; &nbsp; proxy = URL(proxy)
&nbsp; File "C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\yarl\_url.py", line 158, in __new__
&nbsp; &nbsp; raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月14日(星期天) 下午5:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [synodriver/nonebot_plugin_picsearcher] 输入图片后报错 (Issue #10)





 
有完整的traceback吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WindFlarer** [comment]
我是个新手，第一次用别人的插件，请问是直接把nonebot_plugin_picsearcher这个文件夹放到我的机器人文件夹目录下，然后在bot.py里面和env.*里面配置了之后，就能用插件的吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "synodriver/nonebot_plugin_picsearcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [synodriver/nonebot_plugin_picsearcher] 输入图片后报错 (Issue #10)





 
有完整的traceback吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by synodriver** [comment]
可以看看bot.py和配置文件吗？

**Comment by WindFlarer** [comment]
改了proxy还是有点问题
traceback如下
Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py",&nbsp;line&nbsp;969,&nbsp;in&nbsp;_wrap_create_connection
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;await&nbsp;self._loop.create_connection(*args,&nbsp;**kwargs)&nbsp;&nbsp;#&nbsp;type:&nbsp;ignore&nbsp;&nbsp;#&nbsp;noqa
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py",&nbsp;line&nbsp;1081,&nbsp;in&nbsp;create_connection
&nbsp;&nbsp;&nbsp;&nbsp;transport,&nbsp;protocol&nbsp;=&nbsp;await&nbsp;self._create_connection_transport(
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py",&nbsp;line&nbsp;1111,&nbsp;in&nbsp;_create_connection_transport
&nbsp;&nbsp;&nbsp;&nbsp;await&nbsp;waiter
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\asyncio\selector_events.py",&nbsp;line&nbsp;856,&nbsp;in&nbsp;_read_ready__data_received
&nbsp;&nbsp;&nbsp;&nbsp;data&nbsp;=&nbsp;self._sock.recv(self.max_size)
ConnectionResetError:&nbsp;[WinError&nbsp;10054]&nbsp;远程主机强迫关闭了一个现有的连接。

The&nbsp;above&nbsp;exception&nbsp;was&nbsp;the&nbsp;direct&nbsp;cause&nbsp;of&nbsp;the&nbsp;following&nbsp;exception:

Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\nonebot_plugin_picsearcher\__init__.py",&nbsp;line&nbsp;76,&nbsp;in&nbsp;get_setu
&nbsp;&nbsp;&nbsp;&nbsp;async&nbsp;for&nbsp;msg&nbsp;in&nbsp;limiter(get_des(url,&nbsp;mod),&nbsp;bot.config.search_limit&nbsp;or&nbsp;2):
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\nonebot_plugin_picsearcher\utils.py",&nbsp;line&nbsp;9,&nbsp;in&nbsp;limiter
&nbsp;&nbsp;&nbsp;&nbsp;yield&nbsp;await&nbsp;gen.asend(None)
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\nonebot_plugin_picsearcher\__init__.py",&nbsp;line&nbsp;40,&nbsp;in&nbsp;get_des
&nbsp;&nbsp;&nbsp;&nbsp;async&nbsp;for&nbsp;msg&nbsp;in&nbsp;get_des_asc(url):
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\nonebot_plugin_picsearcher\ascii2d.py",&nbsp;line&nbsp;39,&nbsp;in&nbsp;get_des
&nbsp;&nbsp;&nbsp;&nbsp;image_data:&nbsp;List[Tuple]&nbsp;=&nbsp;await&nbsp;get_pic_from_url(url)
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\Desktop\python\QQ机器人4\windflare\nonebot_plugin_picsearcher\ascii2d.py",&nbsp;line&nbsp;33,&nbsp;in&nbsp;get_pic_from_url
&nbsp;&nbsp;&nbsp;&nbsp;async&nbsp;with&nbsp;session.get(real_url,&nbsp;proxy=proxy)&nbsp;as&nbsp;resp:
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py",&nbsp;line&nbsp;1117,&nbsp;in&nbsp;__aenter__
&nbsp;&nbsp;&nbsp;&nbsp;self._resp&nbsp;=&nbsp;await&nbsp;self._coro
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py",&nbsp;line&nbsp;520,&nbsp;in&nbsp;_request
&nbsp;&nbsp;&nbsp;&nbsp;conn&nbsp;=&nbsp;await&nbsp;self._connector.connect(
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py",&nbsp;line&nbsp;535,&nbsp;in&nbsp;connect
&nbsp;&nbsp;&nbsp;&nbsp;proto&nbsp;=&nbsp;await&nbsp;self._create_connection(req,&nbsp;traces,&nbsp;timeout)
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py",&nbsp;line&nbsp;890,&nbsp;in&nbsp;_create_connection
&nbsp;&nbsp;&nbsp;&nbsp;_,&nbsp;proto&nbsp;=&nbsp;await&nbsp;self._create_proxy_connection(req,&nbsp;traces,&nbsp;timeout)
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py",&nbsp;line&nbsp;1139,&nbsp;in&nbsp;_create_proxy_connection
&nbsp;&nbsp;&nbsp;&nbsp;transport,&nbsp;proto&nbsp;=&nbsp;await&nbsp;self._wrap_create_connection(
&nbsp;&nbsp;File&nbsp;"C:\Users\Accepted\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py",&nbsp;line&nbsp;975,&nbsp;in&nbsp;_wrap_create_connection
&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;client_error(req.connection_key,&nbsp;exc)&nbsp;from&nbsp;exc
aiohttp.client_exceptions.ClientConnectorError:&nbsp;Cannot&nbsp;connect&nbsp;to&nbsp;host&nbsp;ascii2d.net:443&nbsp;ssl:default&nbsp;[远程主机强迫关闭了一个现有的连接。]‍



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "synodriver/nonebot_plugin_picsearcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [synodriver/nonebot_plugin_picsearcher] 输入图片后报错 (Issue #10)





 
可以看看bot.py和配置文件吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WindFlarer** [comment]
还有这里不知道为什么是划红线的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "synodriver/nonebot_plugin_picsearcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [synodriver/nonebot_plugin_picsearcher] 输入图片后报错 (Issue #10)





 
可以看看bot.py和配置文件吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WindFlarer** [comment]
感觉还是代理的问题

**Comment by WindFlarer** [comment]
这个问题解决了，就是代理没设置好，但是
![image](https://user-images.githubusercontent.com/94285370/141678820-d252929d-b62d-4e6a-b9ee-d774a23347db.png)
mod和DataclassEncoder在这里是Unresolved reference 导致这个bot在群里用不了

**Comment by synodriver** [comment]
我傻了 ，马上改

**Comment by WindFlarer** [comment]
mod打上引号，然后导入库就行了
![image](https://user-images.githubusercontent.com/94285370/141678985-fcb3b61f-4a91-4d91-a276-b95d5f174107.png)

**Comment by synodriver** [comment]
pip uninstall pip install nonebot-plugin-picsearcher
pip install nonebot-plugin-picsearcher==0.1.6rc1

**Comment by synodriver** [comment]
这个插件一开始是从一个更大的插件拆下来的，用的redis鉴权的，抄过来的时候可能忘了检查结果少了点东西（）

**Comment by WindFlarer** [comment]
原来如此



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月14日(星期天) 晚上7:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [synodriver/nonebot_plugin_picsearcher] 输入图片后报错 (Issue #10)





 
这个插件一开始是从一个更大的插件拆下来的，用的redis鉴权的，抄过来的时候可能忘了检查结果少了点东西（）
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by synodriver** [comment]
ok的话我就关了
