### ISSUE TITLE
beta1 支持

### ISSUE THREAD

**Issue by kexue-z** [synodriver/nonebot_plugin_picsearcher#12]
rt

**Comment by synodriver** [comment]
beta1目前还不稳定……我会开个新branch试试

**Comment by synodriver** [comment]
[beta1](https://github.com/synodriver/nonebot_plugin_picsearcher/tree/beta1) 分支

**Comment by kexue-z** [comment]
好耶

--------------原始邮件--------------
发件人："synodriver ***@***.***&gt;;
发送时间：2022年1月25日(星期二) 下午5:01
收件人："synodriver/nonebot_plugin_picsearcher" ***@***.***&gt;;
抄送："kexue ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [synodriver/nonebot_plugin_picsearcher] beta1 支持 (Issue #12)
-----------------------------------

 

 
beta1 分支
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
