### ISSUE TITLE
不明白怎么使用

### ISSUE THREAD

**Issue by 0xC4FED6C7CCCE** [synodriver/nonebot_plugin_picsearcher#14]
![N3{IEGMP67$~PU}2VI6~P$H](https://user-images.githubusercontent.com/49481572/151746779-e5a4a56e-0457-46b5-8dc0-bc2dcd8d6613.png)
请问咋使用的啊  直接报错

**Comment by synodriver** [comment]
是beta1分支吗？

**Comment by 0xC4FED6C7CCCE** [comment]
main分支

**Comment by synodriver** [comment]
你的nonebot版本？

**Comment by 0xC4FED6C7CCCE** [comment]
nonebot是beta1分支

**Comment by synodriver** [comment]
b1的nonebot得用beta1分支的（他break了）（指nonebot）

**Comment by 0xC4FED6C7CCCE** [comment]
好的谢谢大佬  新年快乐！

**Comment by synodriver** [comment]
我给pypi弄个beta版本吧，正好一对

**Comment by UhUhUh310** [comment]
额，我的2也这个问题，请问怎么解决？

**Comment by synodriver** [comment]
一样的？
