### ISSUE TITLE
输入搜图无反应

### ISSUE THREAD

**Issue by JuuiceP** [synodriver/nonebot_plugin_picsearcher#27]
如题，无论是@还是直接发送“搜图”都无反应

![QQ截图20220520175820](https://user-images.githubusercontent.com/90129856/169504396-641d58e1-d76f-472a-b7e9-fe39c99f345c.png)

**Comment by synodriver** [comment]
试试群聊？

**Comment by JuuiceP** [comment]
emmm   就是在群内发送的搜图。。。

**Comment by synodriver** [comment]
加载了插件吗？看看配置文件和bot.py?

**Comment by JuuiceP** [comment]
如图，看log应该是加载了插件（并没有在bot.py里添加【nonebot.load_plugin('nonebot_plugin_picsearcher')】  添加后会报错）


![QQ截图20220520181820](https://user-images.githubusercontent.com/90129856/169507874-44acc3d4-2aa3-4802-9a34-426f88b2094d.png)
![QQ截图20220520181848](https://user-images.githubusercontent.com/90129856/169507876-f80f11ff-c197-4c44-b219-19514f8b693d.png)

**Comment by synodriver** [comment]
你的版本？

**Comment by JuuiceP** [comment]
我发现一个问题，不光大佬你的插件无法使用，好像使用【on_command（）这个函数的其他插件也没法用， 使用【on_regex（）】函数的倒是可以用，大佬有什么头绪吗

**Comment by synodriver** [comment]
这个问题……回头我去改改nonebot？

**Comment by synodriver** [comment]
你是win系统?执行下```pip list|findstr nonebot```

**Comment by JuuiceP** [comment]
不知道是不是我的问题（也能是nonebot的问题，我看有用户反馈过这个问题
![Uploading QQ截图20220520203925.png…]()

**Comment by JuuiceP** [comment]
不知道是不是我的问题（也能是nonebot的问题，我看有用户反馈过这个问题
![QQ截图20220520203925](https://user-images.githubusercontent.com/90129856/169530117-493c02c7-a5ab-4eec-908f-4451844c52b6.png)

**Comment by synodriver** [comment]
有没有@？

**Comment by JuuiceP** [comment]
无论是否@ 还是叫机器人昵称均无反应

**Comment by synodriver** [comment]
无论群聊私聊，是否at都测试了？

**Comment by JuuiceP** [comment]
输出如下，色图功能倒是正常，或许机器人只想看色图？：）

![QQ截图20220520204932](https://user-images.githubusercontent.com/90129856/169531624-46001da0-1e33-4129-82ef-299f5d7fecad.png)
![QQ截图20220520205022](https://user-images.githubusercontent.com/90129856/169531629-f04eb8f5-de35-4db5-9866-9cd2cad73221.png)

**Comment by synodriver** [comment]
怪……我的怎么可以跑……

**Comment by JuuiceP** [comment]
回头有空我把整个环境重置下再试试吧，谢谢大佬  : ）

**Comment by JuuiceP** [comment]
已解决。原因：我是憨憨
我去看了nonebot的开发手册，发现没在env文件里写【COMMAND_START=[""]】
