### ISSUE TITLE
插件无法正常使用

### ISSUE THREAD

**Issue by broken2211** [synodriver/nonebot_plugin_picsearcher#28]
大佬，显示正常安装，启动正常，qq群聊@或搜图均无反
![_57QFXL6{W` 4FW3W)V}V1R](https://user-images.githubusercontent.com/51013794/169516710-0106edb9-7965-42e3-bcf1-42ae80133afc.png)
![LG }QO1AE5N0PGLZYW~UOZ5](https://user-images.githubusercontent.com/51013794/169516912-9efdbdec-8ca1-4e0b-ae14-9a4021948206.png)
应

**Comment by broken2211** [comment]
版本换成0.17了，可还是不行

**Comment by synodriver** [comment]
能看看日志吗

**Comment by broken2211** [comment]
![C%5M} N9CA~0LG PC4WP`7T](https://user-images.githubusercontent.com/51013794/169591676-f363c49f-2301-4e2c-8963-c24b5232a80a.png)
我好像知道原因了，指令重复了。大佬这怎么改

**Comment by synodriver** [comment]
得把重复的指令改个名字
