### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Luzhopo** [synodriver/nonebot_plugin_picsearcher#29]
显示trace.py中的值写错了
![bot](https://user-images.githubusercontent.com/98378907/169657603-85c59798-722c-4d9f-8d93-060e3ebaadfe.jpg)

**Comment by synodriver** [comment]
马上我发新版

**Comment by synodriver** [comment]
```pip install nonebot-plugin-picsearcher==0.1.8rc1```

**Comment by synodriver** [comment]
现在由action自动发布

**Comment by Luzhopo** [comment]
非常感谢
