### ISSUE TITLE
关于formdata.py的魔改

### ISSUE THREAD

**Issue by Feiyuyu0503** [synodriver/nonebot_plugin_picsearcher#3]
环境是Python 3.8.6
改了formdata.py之后，除了ascii2d源正常处理，其余都报错 AttributeError: 'FormData' object has no attribute '_is_ processed'
然后抄了下这个 https://github.com/aio-libs/aiohttp/blob/master/aiohttp/formdata.py
再加上您的魔改，就好了

**Comment by yoiyami96** [comment]
> 环境是Python 3.8.6
> 改了formdata.py之后，除了ascii2d源正常处理，其余都报错 AttributeError: 'FormData' object has no attribute '_is_ processed'
> 然后抄了下这个 https://github.com/aio-libs/aiohttp/blob/master/aiohttp/formdata.py
> 再加上您的魔改，就好了

你好，我参照你的操作将链接里formdata.py的所有内容替换到了本地的formdata.py，再加上本插件作者的魔改，但依然会报错AttributeError: 'FormData' object has no attribute '_is_ processed'，重装aiohttp后只参照本插件作者的魔改依然会报错，请问有解决办法吗？环境是3.9.2

**Comment by synodriver** [comment]
也许可以在本地打个patch……下个版本看一下，顺便加个代理选项

**Comment by synodriver** [comment]
> > 环境是Python 3.8.6
> > 改了formdata.py之后，除了ascii2d源正常处理，其余都报错 AttributeError: 'FormData' object has no attribute '_is_ processed'
> > 然后抄了下这个 https://github.com/aio-libs/aiohttp/blob/master/aiohttp/formdata.py
> > 再加上您的魔改，就好了
> 
> 你好，我参照你的操作将链接里formdata.py的所有内容替换到了本地的formdata.py，再加上本插件作者的魔改，但依然会报错AttributeError: 'FormData' object has no attribute '_is_ processed'，重装aiohttp后只参照本插件作者的魔改依然会报错，请问有解决办法吗？环境是3.9.2

已经修复了，新版本在本地patch无需魔改了，当然原来的改动也不会有任何影响

**Comment by synodriver** [comment]
https://github.com/synodriver/nonebot_plugin_picsearcher/commit/c25e1db81e06aadcc0bcd9fae3f4d22a443779bb
没问题就可以close了
