### ISSUE TITLE
ASCII2D搜图问题，返回消息中的预览图片加载不出来

### ISSUE THREAD

**Issue by EE0CFF** [synodriver/nonebot_plugin_picsearcher#32]
![image](https://user-images.githubusercontent.com/105940804/169745651-72684a44-5656-4cdb-9ac7-776a5000e2f4.png)

**Comment by synodriver** [comment]
我康康

**Comment by synodriver** [comment]
更新好了，是破机器的bug，自动重构机器还有待改进，起码就目前看来，这机器不能识别到重载运算符导致报错

**Comment by synodriver** [comment]
@sourcery-ai-bot 出来挨打

**Comment by synodriver** [comment]
```pip install -U nonebot-plugin-picsearcher``` 解决之

**Comment by EE0CFF** [comment]
感谢解决XD
