### ISSUE TITLE
运行时报错，ImportError: cannot import name 'State' from 'nonebot.params'

### ISSUE THREAD

**Issue by 19231224lhr** [synodriver/nonebot_plugin_picsearcher#42]
![image](https://user-images.githubusercontent.com/70199004/196587388-f30ec464-9740-4647-a502-d1f45bf8d211.png)
嘤嘤嘤

**Comment by synodriver** [comment]
github的最近一次提交已经修好了，还没来得及发布，想和另一个bug一起修了发，你可以直接安装pip install git+https:// 这样

**Comment by 19231224lhr** [comment]
好的，谢谢大佬~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月19日(星期三) 中午11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [synodriver/nonebot_plugin_picsearcher] 运行时报错，ImportError: cannot import name &#39;State&#39; from &#39;nonebot.params&#39; (Issue #42)





 
github的最近一次提交已经修好了，还没来得及发布，想和另一个bug一起修了发，你可以直接安装pip install git+https:// 这样

**Comment by LumiDust** [comment]
你好，我是今天安装的，目前还是报这个错误 nb是rc1版本

**Comment by 19231224lhr** [comment]
我也还是报错，不知道啥时候会更新版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月3日(周四) 晚上8:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [synodriver/nonebot_plugin_picsearcher] 运行时报错，ImportError: cannot import name 'State' from 'nonebot.params' (Issue #42)

**Comment by synodriver** [comment]
那我先发个rc版本吧，这个版本先别开风控模式，会有bug

**Comment by synodriver** [comment]
先治标
pip install nonebot-plugin-picsearcher==0.1.9.dev1

**Comment by synodriver** [comment]
治本等我明天嫖个号（

**Comment by synodriver** [comment]
定个小目标，看看是nb更新了什么把它搞坏了~~然后向ddl兴师问罪~~

**Comment by synodriver** [comment]
pip install -U nonebot-plugin-picsearcher 修好了
