### ISSUE TITLE
搜索报错

### ISSUE THREAD

**Issue by LumiDust** [synodriver/nonebot_plugin_picsearcher#43]
![YPE T5 T7Q6Y{ZB12$AZFJ9](https://user-images.githubusercontent.com/116658416/199908330-59c53c28-d167-4842-a9d1-a40a703b5e23.png)
![IS`(9PXS0@ N7@95`I S7@7](https://user-images.githubusercontent.com/116658416/199908357-6d197fb8-d49e-4e9d-9eab-d2155db89dbb.png)
代理和cookie都填好了，搜索后台报错

**Comment by synodriver** [comment]
老bug，明天我看看，可以先试试pip install nonebot-plugin-picsearcher==0.1.9.dev1

**Comment by synodriver** [comment]
pip install -U nonebot-plugin-picsearcher 修好了

**Comment by LumiDust** [comment]
感谢
