### ISSUE TITLE
建议添加群内搜图结果数量限制 防止结果过多刷屏

### ISSUE THREAD

**Issue by kexue-z** [synodriver/nonebot_plugin_picsearcher#5]
建议添加群内搜图结果数量限制 防止结果过多刷屏
对于群聊搜索返回的结果 可以只发送一个匹配程度的最高的结果 剩余结果尝试使用私聊发送

尤其是指令 `上一张` `这是什么` 误触发时搜索结果刷屏

**Comment by synodriver** [comment]
但是全部私聊可能会被风控

**Comment by xana278** [comment]
那可以让群聊触发 `上一张` `这是什么`指令时的返回结果只保留匹配最高的。

**Comment by synodriver** [comment]
等下我改改

**Comment by synodriver** [comment]
改成可以配置的吧

**Comment by synodriver** [comment]
[修好了](https://pypi.org/project/nonebot-plugin-picsearcher/0.1.5rc1/)
