### ISSUE TITLE
trace.moe返回的数据格式发生的变化

### ISSUE THREAD

**Issue by ColdThunder11** [synodriver/nonebot_plugin_picsearcher#6]
新的格式里anilist只有id了，还有trace.py line 60 的FormData错误用成了aiohttp原版的
        {
            "anilist": 20740,
            "filename": "[HYSUB]Yamada-kun to 7-nin no Majo[OAD][01][BIG5_MP4][1024X576].mp4",
            "episode": 1,
            "from": 360.33,
            "to": 363.17,
            "similarity": 0.8345495133319203,
            "video": "https://media.trace.moe/video/20740/%5BHYSUB%5DYamada-kun%20to%207-nin%20no%20Majo%5BOAD%5D%5B01%5D%5BBIG5_MP4%5D%5B1024X576%5D.mp4?t=361.75&token=zrW69bECSDUNg9vQ7MRP02jU",
            "image": "https://media.trace.moe/image/20740/%5BHYSUB%5DYamada-kun%20to%207-nin%20no%20Majo%5BOAD%5D%5B01%5D%5BBIG5_MP4%5D%5B1024X576%5D.mp4?t=361.75&token=zrW69bECSDUNg9vQ7MRP02jU"
        }

**Comment by synodriver** [comment]
是trace.moe自身发生了变化吗？

**Comment by synodriver** [comment]
POST https://api.trace.moe/search?cutBorders&
:authority: api.trace.moe
:method: POST
:path: /search?cutBorders&
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
content-length: 18679
content-type: multipart/form-data; boundary=----WebKitFormBoundaryWizMJmFjBjT38e7F
origin: https://trace.moe
referer: https://trace.moe/
sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Microsoft Edge";v="92"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.55

**Comment by synodriver** [comment]
> POST https://api.trace.moe/search?cutBorders&
> :authority: api.trace.moe
> :method: POST
> :path: /search?cutBorders&
> :scheme: https
> accept: _/_
> accept-encoding: gzip, deflate, br
> accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
> content-length: 18679
> content-type: multipart/form-data; boundary=----WebKitFormBoundaryWizMJmFjBjT38e7F
> origin: https://trace.moe
> referer: https://trace.moe/
> sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Microsoft Edge";v="92"
> sec-ch-ua-mobile: ?0
> sec-fetch-dest: empty
> sec-fetch-mode: cors
> sec-fetch-site: same-site
> user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.55
我抓到的是这个

**Comment by synodriver** [comment]
其实boundary不用管倒是真的

**Comment by ColdThunder11** [comment]
> 是trace.moe自身发生了变化吗？

![image](https://user-images.githubusercontent.com/34985592/127100616-a2df739d-030d-4627-bc9c-a6586e65bedf.png)
anilist字段已经变成id了，需要通过post https://trace.moe/anilist 再去查询其他信息

**Comment by synodriver** [comment]
这就改

**Comment by synodriver** [comment]
简直可怕，居然post的是pretty的body上去（

**Comment by ColdThunder11** [comment]
离谱(

**Comment by synodriver** [comment]
那东西甚至不是合法的json字符串，格式化之后才是
```
{'query': 'query ($ids: [Int]) {Page(page: 1, perPage: 50) {media(id_in: $ids, type: ANIME) {id title {native  romaji english } type format status startDate { year month day }  endDate { ', 'variables': {'ids': [942, 20906, 20906, 98005, 114232]}}
```
我是后端的话得把这前端揍一顿

**Comment by synodriver** [comment]
今天应该可以修好

**Comment by synodriver** [comment]
看最新的commit
