### ISSUE TITLE
使用合并转发消息而不是直接发

### ISSUE THREAD

**Issue by synodriver** [synodriver/nonebot_plugin_picsearcher#8]
防止风控

**Comment by synodriver** [comment]
fixed in https://github.com/synodriver/nonebot_plugin_picsearcher/commit/af9bc3f92b16f14e26dc7871a65a5865d1510f66

**Comment by lgc2333** [comment]
> fixed in [af9bc3f](https://github.com/synodriver/nonebot_plugin_picsearcher/commit/af9bc3f92b16f14e26dc7871a65a5865d1510f66)

合并转发消息会风控，建议还是提供过滤r18选项
